/**
 * API Surface Lock – contract drift guard.
 *
 * Builds every package, collects the public .d.ts declarations and compares
 * them against the checked-in reports in `etc/<package>.api.md`.
 *
 * Usage:
 *   node scripts/api-lock.mjs           – verify (CI mode, exits non-zero on drift)
 *   node scripts/api-lock.mjs --update  – regenerate the report files
 */

import { execSync } from "node:child_process";
import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const packagesDir = join(repoRoot, "packages");
const etcDir = join(repoRoot, "etc");

const update = process.argv.includes("--update");

async function listDtsFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listDtsFiles(full)));
    } else if (entry.name.endsWith(".d.ts")) {
      files.push(full);
    }
  }
  return files.sort();
}

async function buildReport(pkgDir) {
  const distDir = join(pkgDir, "dist");
  let files;
  try {
    files = await listDtsFiles(distDir);
  } catch {
    return null;
  }

  if (files.length === 0) return null;

  const lines = [];
  for (const file of files) {
    const rel = relative(pkgDir, file);
    const content = (await readFile(file, "utf8"))
      .split("\n")
      .filter((l) => !l.startsWith("//# sourceMappingURL="))
      .join("\n")
      .trimEnd();
    lines.push(`## ${rel}\n`);
    lines.push("```ts");
    lines.push(content);
    lines.push("```\n");
  }

  return lines.join("\n");
}

async function main() {
  // 1. Clean previous build output for a fresh declaration pass
  const pkgEntries = (
    await readdir(packagesDir, { withFileTypes: true })
  ).filter((d) => d.isDirectory());
  for (const d of pkgEntries) {
    await rm(join(packagesDir, d.name, "dist"), { recursive: true, force: true });
  }

  // 2. Build packages (continue on individual package errors so .d.ts files are still emitted)
  console.log("Building packages…");
  try {
    execSync("pnpm -r --filter './packages/**' run build", {
      cwd: repoRoot,
      stdio: "inherit",
    });
  } catch {
    // Individual package builds may fail; tsc still emits declaration files.
  }

  // 3. Collect package names
  const dirs = pkgEntries;

  await mkdir(etcDir, { recursive: true });

  let drifted = false;

  for (const dir of dirs) {
    const pkgDir = join(packagesDir, dir.name);
    const report = await buildReport(pkgDir);
    if (!report) continue;

    const header = `# API Report – ${dir.name}\n\n> Do not edit this file. It is generated by \`node scripts/api-lock.mjs --update\`.\n\n`;
    const full = header + report;
    const reportPath = join(etcDir, `${dir.name}.api.md`);

    if (update) {
      await writeFile(reportPath, full);
      console.log(`  ✔ updated ${relative(repoRoot, reportPath)}`);
    } else {
      let existing;
      try {
        existing = await readFile(reportPath, "utf8");
      } catch {
        console.error(`  ✖ missing report: ${relative(repoRoot, reportPath)}`);
        console.error(`    Run: node scripts/api-lock.mjs --update`);
        drifted = true;
        continue;
      }

      if (existing !== full) {
        console.error(`  ✖ drift detected: ${relative(repoRoot, reportPath)}`);
        console.error(`    Run: node scripts/api-lock.mjs --update`);
        drifted = true;
      } else {
        console.log(`  ✔ ${dir.name}`);
      }
    }
  }

  if (drifted) {
    console.error(
      "\nAPI surface has drifted. Run `node scripts/api-lock.mjs --update` and commit the changes."
    );
    process.exit(1);
  }

  console.log(update ? "\nReports updated." : "\nNo drift detected.");
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
